---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      initContainers:
      - name: vol-init
        image: busybox
        command:
        - /bin/sh
        - -c
        - "mkdir -p /exports/pvc && chown -R 1000:1000 /exports/pvc"
        volumeMounts:
        - name: storage
          mountPath: /exports
      containers:
      - name: nfs-server
        image: ghcr.io/n-arno/volume-nfs:updated
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        volumeMounts:
        - name: storage
          mountPath: /exports
        securityContext:
          privileged: true
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: nfs-data
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  clusterIP: 10.32.100.<num> # use fixed cluster ip because host can't resolve service name
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: nfs-server
